# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.ki-decentralized.de:
  peer0.turktelekom.com:
  peer1.turktelekom.com:
  peer0.turkcell.com:
  peer1.turkcell.com:
  peer0.vodafone.com:
  peer1.vodafone.com:

networks:
  byfn:

services:
  ca.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.turktelekom.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/39ac72643fe7c559eb31a91e13a91fcaffc57f753c48d4f4e13faa146767e8a4_sk
      # C1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/turktelekom.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.example.com
    networks:
      - byfn

  orderer.ki-decentralized.de:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.ki-decentralized.de
    container_name: orderer.ki-decentralized.de
    networks:
      - byfn

  peer0.turktelekom.com:
    container_name: peer0.turktelekom.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.turktelekom.com
    networks:
      - byfn

  peer1.turktelekom.com:
    container_name: peer1.turktelekom.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.turktelekom.com
    networks:
      - byfn

  peer0.turkcell.com:
    container_name: peer0.turkcell.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.turkcell.com
    networks:
      - byfn

  peer1.turkcell.com:
    container_name: peer1.turkcell.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.turkcell.com
    networks:
      - byfn

  peer0.vodafone.com:
    container_name: peer0.vodafone.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.vodafone.com
    networks:
      - byfn

  peer1.vodafone.com:
    container_name: peer1.vodafone.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.vodafone.com
    networks:
      - byfn

  # caturktelekom:
  #   image: hyperledger/fabric-ca
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=caturktelekom
  #     - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.turktelekom.com-cert.pem
  #     - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/12268a8918423c494629325c47e50466dd694f7000952c14e2cfda6a774bf418_sk
  #   ports:
  #     - "7054:7054"
  #   command: sh -c 'fabric-ca-server start --config /etc/hyperledger/fabric-ca-server-config/ca_config.yaml -d -b admin:adminpw'
  #   volumes:
  #     - /Users/t.ish/Desktop/DLT-telco/code/dlt-fabric-use-case-telco/crypto-config/peerOrganizations/turktelekom.com/ca:/etc/hyperledger/fabric-ca-server-config
  #   container_name: caturktelekom
  #   networks:
  #     - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.turktelekom.com:7051
      - CORE_PEER_LOCALMSPID=TurkTelekomMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/turktelekom.com/peers/peer0.turktelekom.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/turktelekom.com/peers/peer0.turktelekom.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/turktelekom.com/peers/peer0.turktelekom.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/turktelekom.com/users/Admin@turktelekom.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      # - orderer.ki-decentralized.de
      - orderer.ki-decentralized.de
      - peer0.turktelekom.com
      - peer1.turktelekom.com
      - peer0.turkcell.com
      - peer1.turkcell.com
      - peer0.vodafone.com
      - peer1.vodafone.com
    networks:
      - byfn
