version: '2'

volumes:
  orderer.ki-decentralized.de:
  peer0.regulator.com:
  peer1.regulator.com:
  peer0.shipper.com:
  peer1.shipper.com:
  peer0.carrier.com:
  peer1.carrier.com:

networks:
  byfn:

services:
  ca.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.regulator.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/43fc2aa6646664406e60115227c870592790b4030093ae82c3bd999b993cdf4e_sk
      # C1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/regulator.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.example.com
    networks:
      - byfn

  orderer.ki-decentralized.de:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.ki-decentralized.de
    container_name: orderer.ki-decentralized.de
    networks:
      - byfn

  peer0.regulator.com:
    container_name: peer0.regulator.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.regulator.com
    depends_on:
      - couchdb
    networks:
      - byfn

  peer1.regulator.com:
    container_name: peer1.regulator.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.regulator.com
    networks:
      - byfn

  peer0.shipper.com:
    container_name: peer0.shipper.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.shipper.com
    networks:
      - byfn

  peer1.shipper.com:
    container_name: peer1.shipper.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.shipper.com
    networks:
      - byfn

  peer0.carrier.com:
    container_name: peer0.carrier.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.carrier.com
    networks:
      - byfn

  peer1.carrier.com:
    container_name: peer1.carrier.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.carrier.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.regulator.com:7051
      - CORE_PEER_LOCALMSPID=RegulatorMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/regulator.com/peers/peer0.regulator.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/regulator.com/peers/peer0.regulator.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/regulator.com/peers/peer0.regulator.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/regulator.com/users/Admin@regulator.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.ki-decentralized.de
      - peer0.regulator.com
      - peer1.regulator.com
      - peer0.shipper.com
      - peer1.shipper.com
      - peer0.carrier.com
      - peer1.carrier.com
      - couchdb
    networks:
      - byfn
  
  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - byfn
