version: '2'

services:

  orderer.ki-decentralized.de:
    container_name: orderer.ki-decentralized.de
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/ki-decentralized.de/orderers/orderer.ki-decentralized.de/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/ki-decentralized.de/orderers/orderer.ki-decentralized.de/tls/:/var/hyperledger/orderer/tls
    - orderer.ki-decentralized.de:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.regulator.com:
    container_name: peer0.regulator.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.regulator.com
      - CORE_PEER_ADDRESS=peer0.regulator.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.regulator.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.regulator.com:7051
      - CORE_PEER_LOCALMSPID=TurkTelekomMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/regulator.com/peers/peer0.regulator.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/regulator.com/peers/peer0.regulator.com/tls:/etc/hyperledger/fabric/tls
        - peer0.regulator.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.regulator.com:
    container_name: peer1.regulator.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.regulator.com
      - CORE_PEER_ADDRESS=peer1.regulator.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.regulator.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.regulator.com:7051
      - CORE_PEER_LOCALMSPID=TurkTelekomMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/regulator.com/peers/peer1.regulator.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/regulator.com/peers/peer1.regulator.com/tls:/etc/hyperledger/fabric/tls
        - peer1.regulator.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.shipper.com:
    container_name: peer0.shipper.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.shipper.com
      - CORE_PEER_ADDRESS=peer0.shipper.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.shipper.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.shipper.com:7051
      - CORE_PEER_LOCALMSPID=TurkcellMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/shipper.com/peers/peer0.shipper.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/shipper.com/peers/peer0.shipper.com/tls:/etc/hyperledger/fabric/tls
        - peer0.shipper.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.shipper.com:
    container_name: peer1.shipper.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.shipper.com
      - CORE_PEER_ADDRESS=peer1.shipper.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.shipper.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.shipper.com:7051
      - CORE_PEER_LOCALMSPID=TurkcellMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/shipper.com/peers/peer1.shipper.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/shipper.com/peers/peer1.shipper.com/tls:/etc/hyperledger/fabric/tls
        - peer1.shipper.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.carrier.com:
    container_name: peer0.carrier.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.carrier.com
      - CORE_PEER_ADDRESS=peer0.carrier.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.carrier.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.carrier.com:7051
      - CORE_PEER_LOCALMSPID=VodafoneMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/carrier.com/peers/peer0.carrier.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/carrier.com/peers/peer0.carrier.com/tls:/etc/hyperledger/fabric/tls
        - peer0.carrier.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.carrier.com:
    container_name: peer1.carrier.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.carrier.com
      - CORE_PEER_ADDRESS=peer1.carrier.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.carrier.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.carrier.com:7051
      - CORE_PEER_LOCALMSPID=VodafoneMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/carrier.com/peers/peer1.carrier.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/carrier.com/peers/peer1.carrier.com/tls:/etc/hyperledger/fabric/tls
        - peer1.carrier.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
